// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCommand'](arg1, arg2, arg3);
}

export function CopyCommand(arg1) {
  return window['go']['main']['App']['CopyCommand'](arg1);
}

export function GetCommands() {
  return window['go']['main']['App']['GetCommands']();
}

export function GetContexts() {
  return window['go']['main']['App']['GetContexts']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function Search(arg1, arg2) {
  return window['go']['main']['App']['Search'](arg1, arg2);
}
