// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';
import {context} from '../models';

export function AddCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CopyCommand(arg1:string):Promise<void>;

export function DeleteCommand(arg1:string):Promise<void>;

export function GetCommands():Promise<Array<core.Command>>;

export function GetContexts():Promise<Array<string>>;

export function GetSettings():Promise<core.Settings>;

export function Refresh():Promise<void>;

export function SaveSettings(arg1:core.Settings):Promise<void>;

export function Search(arg1:string,arg2:string):Promise<Array<main.searchResult>>;

export function SetContext(arg1:context.Context):Promise<void>;
