Output assets/gifs/decoreba-add.gif
Set FontSize 20
Set Theme Dracula
Set Padding 40

Type "decoreba add"
Sleep 200ms
Enter
Sleep 1.5s
Type "git"
Sleep 300ms
Tab
Sleep 400ms
Type "pretty git log"
Sleep 400ms
Tab
Sleep 300ms
Type "git log --oneline --graph --all --decorate"
Sleep 400ms
Tab
Sleep 300ms
Type "git, logs, graph"
Sleep 300ms
Tab
Sleep 300ms
Type "Compact graph of all branches"
Sleep 500ms
Enter
Sleep 3s
